//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sudoku {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Message {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Message() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sudoku.Message", typeof(Message).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///d88PPPo 888   88   ,d8PPPP
        ///888ooo8 888ooo88   d88ooo
        ///888   8       88 ,88&apos;
        ///888PPPP PPPPPP8P 88bdPPP.
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///_______  _______  _        _______  _______  _______ __________________ _        _______
        ///(  ____ \(  ____ \( (    /|(  ____ \(  ____ )(  ___  )\__   __/\__   __/( (    /|(  ____ \
        ///| (    \/| (    \/|  \  ( || (    \/| (    )|| (   ) |   ) (      ) (   |  \  ( || (    \/
        ///| |      | (__    |   \ | || (__    | (____)|| (___) |   | |      | |   |   \ | || |
        ///| | ____ |  __)   | (\ \) ||  __)   |     __)|  ___  |   | |      | |   | (\ \) || | ____
        ///| | \_  )| (      | | \   || (      | (\ (   | (   ) |   |  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Generate {
            get {
                return ResourceManager.GetString("Generate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///_ __    _ .___  .     .  _______
        /// | |\   |  /   \ /     / &apos;   /
        /// | | \  |  |,_-&apos; |     |     |
        /// | |  \ |  |     |     |     |
        /// / |   \|  /      `._.&apos;      /.
        /// </summary>
        internal static string Input {
            get {
                return ResourceManager.GetString("Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        /// _ __  _  _   _   __  _   _ __
        ///| |  \| || \ / | /  \| | | | _\
        ///| | | &apos; |`\ V /&apos;| /\ | |_| | v |
        ///|_|_|\__|  \_/  |_||_|___|_|__/.
        /// </summary>
        internal static string Invalid {
            get {
                return ResourceManager.GetString("Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///.---. .-..-..-.    .--.  .--.
        ///: .; :: :: :: :   : .--&apos;: .--&apos;
        ///:   .&apos;: :: :: :   : `;  `. `.
        ///: :.`.: :; :: :__ : :__  _`, :
        ///:_;:_;`.__.&apos;:___.&apos;`.__.&apos;`.__.&apos;.
        /// </summary>
        internal static string Rules {
            get {
                return ResourceManager.GetString("Rules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///   _____ ____  __ _    _______   ________
        ///  / ___// __ \/ /| |  / /  _/ | / / ____/
        ///  \__ \/ / / / / | | / // //  |/ / / __
        /// ___/ / /_/ / /__| |/ // // /|  / /_/ /
        ////____/\____/_____/___/___/_/ |_/\____/.
        /// </summary>
        internal static string Solve {
            get {
                return ResourceManager.GetString("Solve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .d8888. db    db d8888b.  .d88b.  db   dD db    db
        ///88&apos;  YP 88    88 88  `8D .8P  Y8. 88 ,8P&apos; 88    88
        ///`8bo.   88    88 88   88 88    88 88,8P   88    88
        ///  `Y8b. 88    88 88   88 88    88 88`8b   88    88
        ///db   8D 88b  d88 88  .8D `8b  d8&apos; 88 `88. 88b  d88
        ///`8888Y&apos; ~Y8888P&apos; Y8888D&apos;  `Y88P&apos;  YP   YD ~Y8888P&apos;.
        /// </summary>
        internal static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        /// __   __   ___     _       ___     ___
        /// \ \ / /  /   \   | |     |_ _|   |   \
        ///  \ V /   | - |   | |__    | |    | |) |
        ///  _\_/_   |_|_|   |____|  |___|   |___/
        ///_| &quot;&quot;&quot;&quot;|_|&quot;&quot;&quot;&quot;&quot;|_|&quot;&quot;&quot;&quot;&quot;|_|&quot;&quot;&quot;&quot;&quot;|_|&quot;&quot;&quot;&quot;&quot;|
        ///&quot;`-0-0-&apos;&quot;`-0-0-&apos;&quot;`-0-0-&apos;&quot;`-0-0-&apos;&quot;`-0-0-&apos;.
        /// </summary>
        internal static string Valid {
            get {
                return ResourceManager.GetString("Valid", resourceCulture);
            }
        }
    }
}
